language: node_js
node_js:
- 10
- 8
addons:
  code_climate:
    repo_token:
      secure: "433qFGGS8nDgKAD7X5yD8G0I12I/i3I5zlmND3kN71FDa+o6PAlGyIDcfeARJntCTsTWq0EHJosOlQq2xHZF6yn1DErsvv0GqnD4UuMMVvHFXWfbHORikJeOlKAuSAYkuyxzxagPAoPc8A6z0BvwStwExYslVu/EiswE9DRORNDYpw1R2D5PgyhizZCVaJn16MImG5ld6/4hNl2I0c9+luMXkg3ZTaxwsqJDMmPhmEJLfbYhQHeTmythALYTZGSTr43ZFS+giqrNHdztZevVlvuSMC3zteOQzMY83EM6kz+lJ/b1pZkwUgPoRZLBX8LopKhFkywicj8sSdQSmP08ws1j7i7TXfeWGHYh9aJ6R93O9EBSuZD3ePms+2SStgx8uhQ17y4cvBiUM00Vw40YqUdUjqKZGXyYpAnaEaqRFaxBwAHOwc+Ny/kJTiEwKewyCV2yGZp2QzcJRHeGMqF8Rbg41m9rEcnr2QgSnyMMAM674hpq8P15TYUSozpBsPlj69rnRah1WLe6VitnAIZoO98A21Y4CcL4w/7Pt+f0P4oy161N9GSdjPMW4Q70pHC+tUMeOY/Ni9hzPr7Q/R/DGpNxZAKw9CwC/WoUCizwgjX5gBEAX08Hfgfzi3++7vVzgH3aG9Wp0muSV4rUV9KDRlChCcmvFEG86nihP/ILtpA="
script: npm run test:coverage
before_script:
- npm install codeclimate-test-reporter -g
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
notifications:
  email:
    recipients:
    - pritishvaidya94@gmail.com
    on_success: never
    on_failure: always
